"""
supabase_client.py
Inisialisasi klien Supabase (untuk histori evaluasi & penyimpanan model opsional).
Environment variables diambil dari Vercel Project Settings atau file .env lokal.
"""

import os
from functools import lru_cache

from supabase import Client, create_client


@lru_cache(maxsize=1)
def get_supabase_client() -> Client:
    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not url or not key:
        raise RuntimeError(
            "SUPABASE_URL / SUPABASE_SERVICE_KEY belum diset. "
            "Tambahkan di file .env (lokal) atau Environment Variables (Vercel)."
        )
    return create_client(url, key)


"""
SQL untuk membuat tabel di Supabase (jalankan di SQL Editor Supabase):

create table training_runs (
    id bigint generated by default as identity primary key,
    k_value integer not null,
    accuracy numeric,
    precision numeric,
    recall numeric,
    f1_score numeric,
    created_at timestamp with time zone default now()
);

-- (opsional) bucket Storage untuk menyimpan model custom & CSV upload:
-- Buat via Dashboard Supabase -> Storage -> New Bucket -> "models" dan "datasets"
"""
